name: release-tag

on:
  push: 
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: tag 추출
        id: tag
        uses: dawidd6/action-get-tag@master
        with:
          strip_v: true

      - name: Release 생성 
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          release_name: ${{ steps.tag.outputs.tag }}